[project]
name = "pg-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "mcp[cli]>=1.5.0",
    "pydantic-ai>=0.0.46",
]
